schema: apps/server/src/interfaces/graphql/**/*.graphql

documents: apps/web/src/**/*.graphql

extensions:
  diff:
    baseSchema: git:origin/master:apps/server/schema.generated.graphql

  codegen:
    hooks:
      afterAllFileWrite:
        - prettier --write

    overwrite: true

    generates:
      apps/fake-server/src/schema.generated.json:
        plugins:
          - introspection

      apps/server/schema.generated.graphql:
        plugins:
          - schema-ast
        config:
          includeDirectives: true

      apps/server/src/types/resolvers.generated.ts:
        plugins:
          - typescript
          - typescript-resolvers
        config:
          contextType: ../interfaces/graphql/context#Context
          fieldContextTypes:
            - Mutation.updateProfile#../interfaces/graphql/context#AuthenticatedContext
            - Mutation.borrowBookCopy#../interfaces/graphql/context#AuthenticatedContext
            - Mutation.returnBookCopy#../interfaces/graphql/context#AuthenticatedContext
            - Mutation.addBookToFavourites#../interfaces/graphql/context#AuthenticatedContext
            - Mutation.removeBookFromFavourites#../interfaces/graphql/context#AuthenticatedContext
            - Mutation.createReview#../interfaces/graphql/context#AuthenticatedContext
          mappers:
            Author: ../infra/database/entity#Author
            Avatar: ../infra/database/entity#Avatar
            Book: ../infra/database/entity#Book
            BookCopy: ../infra/database/entity#BookCopy
            PublicUser: ../infra/database/entity#User
            ProtectedUser: ../infra/database/entity#User
            Review: ../infra/database/entity#Review
          mapperTypeSuffix: Entity
          optionalResolveType: true
          scalars:
            ExternalID: string
            ISODateString: string
          showUnusedMappers: true
          noSchemaStitching: true
          immutableTypes: true

      apps/web/src:
        plugins:
          - typescript-operations
          - typescript-react-apollo
        config:
          gqlImport: "@apollo/client#gql"
          avoidOptionals: true
        preset: near-operation-file-preset
        presetConfig:
          baseTypesPath: types.generated.ts
          extension: .generated.tsx

      apps/web/src/introspectionResult.generated.ts:
        plugins:
          - fragment-matcher

      apps/web/src/types.generated.ts:
        plugins:
          - typescript
