schema: apps/server/src/graphql/**/*.graphql

documents: apps/web/src/**/*.graphql

extensions:
  diff:
    baseSchema: git:origin/master:apps/server/schema.generated.graphql

  codegen:
    hooks:
      afterAllFileWrite:
        - prettier --write

    overwrite: true

    generates:
      apps/fake-server/src/schema.generated.json:
        plugins:
          - introspection

      apps/server/schema.generated.graphql:
        config:
          includeDirectives: true
        plugins:
          - schema-ast

      apps/server/src/graphql/resolvers-types.generated.ts:
        config:
          mappers:
            Author: ../database/entity#Author
            Avatar: ../database/entity#Avatar
            Book: ../database/entity#Book
            BookCopy: ../database/entity#BookCopy
            PublicUser: ../database/entity#User
            ProtectedUser: ../database/entity#User
          mapperTypeSuffix: Entity
          optionalResolveType: true
          scalars:
            ExternalID: string
            ISODateString: string
          showUnusedMappers: true
        plugins:
          - typescript
          - typescript-resolvers

      apps/web/src:
        plugins:
          - typescript-operations
          - typescript-react-apollo
        config:
          gqlImport: '@apollo/client#gql'
          avoidOptionals: true
        preset: near-operation-file-preset
        presetConfig:
          baseTypesPath: types.generated.ts
          extension: .generated.tsx

      apps/web/src/introspectionResult.generated.ts:
        config:
          apolloClientVersion: 3
        plugins:
          - fragment-matcher

      apps/web/src/types.generated.ts:
        plugins:
          - typescript
