defaultSemverRangePrefix: ""

nodeLinker: node-modules

packageExtensions:
  "@apollo/client@*":
    dependencies:
      graphql: "*"
  "@apollographql/apollo-tools@*":
    dependencies:
      graphql: "*"
  typeorm@*:
    dependencies:
      pg: "*"
      sqlite3: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-2.3.3.cjs
