name: bookshelf

services:
  db-development:
    image: postgres:15.2
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookshelf_development
